### ISSUE TITLE
PrimeUI dead? Please clarify about project status.

### ISSUE THREAD

**Issue by cnsgithub** [primefaces/primeui#264]
As it was already asked here - but without response 
http://forum.primefaces.org/viewtopic.php?f=16&t=48547

So i may ask as well:

Is PrimeUI dead? Was it replaced by PrimeNG? 

It would be good to know if it should be used for new project and if old project should be migrated to something else. Thanks!

**Comment by sudheerj** [comment]
I don't have details about PrimeUI roadmap.Cagatay only can respond on this.

PrimeUI is a pure HTML,JS and jquery widget based UI component library where as PrimeNG is an UI Component suite for Angular2 with pure native components(except one or two components based on other third part JS libs).So if you want to opt Angular2 then go for PrimeNG otherwise you can opt for PrimeUI.

**Comment by onursenture** [comment]
There is an answer on the link that you sent actually.
